vidli_Full_App/Vidly/Models/Rental.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Vidly.Models
{
    public class Rental
    {
        public int Id { get; set; }

        [Required]
        public Customer Customer { get; set; }

        [Required]
        public Movie Movie { get; set; }
        
        public DateTime DateRented { get; set; }

    }
}

vidli_Full_App/Vidly/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    [Authorize(Roles = RoleName.CanManageMovies)]
    public class RentalsController : Controller
    {
        private ApplicationDbContext _context;

        public RentalsController()
        {
            _context = new ApplicationDbContext();
        }

        
        public ViewResult New()
        {
            //public List<int> movieIds = _context.Movie();
            var viewModel = new RentalFormViewModel();

            var moviesList =_context.Movies.ToList();
            var mList = new List<SelectListItem>();
            foreach(var movie in moviesList)
            {
                var selectList = new SelectListItem
                {
                    Text = movie.Name,
                    Value = movie.Id.ToString()
                };
                mList.Add(selectList);
            }

            var customerLists = _context.Customers.ToList();
            var cList = new List<SelectListItem>();
            foreach (var customer in customerLists)
            {
                var selectList = new SelectListItem
                {
                    Text = customer.Name,
                    Value = customer.Id.ToString()
                };
                cList.Add(selectList);
            }
            viewModel.Movies = mList;
            viewModel.Customers = cList;

            return View("RentalForm", viewModel);
        }

        [HttpPost]
        public ViewResult New(RentalFormViewModel newRental)
        {
            if (!ModelState.IsValid)
            {
                return View("RentalForm");
            }
            int SCID = int.Parse(newRental.SelectedCustomerID);
            var customer = _context.Customers.Single(c => c.Id == SCID);

            int SMID = int.Parse(newRental.SelectedMovieID);
            var movie = _context.Movies.Single(c => c.Id == SMID);


            ViewBag.NumberAvail = movie.NumberAvailable;
            ViewBag.Success = false;
            if (movie.NumberAvailable == 0)        // Edge Case => Optimistic
             {
                return View("ConfirmPage");
             }

             movie.NumberAvailable--;  // decreasing 
             ViewBag.Success = true;
             ViewBag.NumberAvail--;

            var rental = new Rental  // rental object
             {
                    Customer = customer,
                    Movie = movie,
                    DateRented = DateTime.Now
             };
             _context.Rentals.Add(rental);
             _context.SaveChanges();
            
            return View("ConfirmPage");
        }
    }
}

vidli_Full_App/Vidly/Views/Rentals/ConfirmPage.cshtml
@{
    ViewBag.Title = "ConfermPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirmation Page</h2>
<br />

@if (ViewBag.Success)
{
    <h3>Your booking has completed</h3>
}
else
{
    <h3>Your booking has not been completed</h3>
}

<li>Number of available movie = @ViewBag.NumberAvail</li>
<li>Success = <b> @ViewBag.Success </b></li>

<br />
<br />

@Html.ActionLink("Back to Movies List", "New", "Rentals")

vidli_Full_App/Vidly/Views/Rentals/New.cshtml
@{
    ViewBag.Title = "New Rental Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Rental Form</h2>

<form id="NewRental">
    <!-- ZenCoding-->
    <div class="form-group">
        <label>Customer</label>
        <div class="tt-container">
            <input id="customer" name="customer" data-rule-validCustomer="true"  required type="text" value="" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label>Movie</label>
        <div class="tt-container">
            <input id="movie" name="movie" type="text" value="" class="form-control" />
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-sm-4">
            <ul id="movies" class="list-group"></ul>
        </div>
    </div>

    <button class="btn btn-primary">Submit</button>
</form>
@section scripts
{
   @* $Scripts.Render("~/bundles/jqueryval");   *@
    <script>
        $(document).ready(function () {
            // For Customers
            var vm = {
                MovieId: []
            };

            var customers = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('Name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,

                remote: {
                    url: '/api/customers?query=%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('#customer').typeahead({
                minLenght: 3,
                highlight: true

            }, {
                name: 'customers',
                display: 'Name',
                source: customers
            }).on("typeahead:select", function (e, customer) {
                vm.customerid = customer.id;

            });

            // For movies

            var movies = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('Name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: '/api/movies?query=%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('#movie').typeahead({
                minLength: 3,
                highlight: true
            },
                {
                    name: 'movie',
                    display: 'Name',
                    source: movies
                }).on("typeahead:select", function (e, movie) {
                    $("#movies").append("<li class='list-group-item'>" + movie.Name + "</li>");

                    $("#movies").typeahead("val", "");

                    vm.MovieId.push(movie.id);
                });
        // custom validator for customer
            //$.validator.addMethod("validCustomer", function () {
            //    return vm.customerid != 0;
            //});

            // custom validator for movies
            //$.validator.addMethod("atLeastOneMovie", function () {
            //    return vm.movieIds.length > 0;
            //}, "Please select at least one movie. ");

         //var validator =   $("#NewRental").validate({
                //submitHandler: function () {

            $("#NewRental").submit(function (e) {
                    e.preventDefault();
                    $.ajax({
                        url: "/api/NewRentals",
                        method: "Post",
                        data: vm
                    })
                        .done(function () {
                            toastr.success("Rentals successfully recorded.")

                            $("#customer").typeahead("val", "");
                            $("#movie").typeahead("val", "");
                            $("#movies").typeahead("val", "");

                            vm = { movieIds: [] };

                            validator.resetForm();
                        })
                        .fail(function () {
                            toastr.error("Something unexpected happened")
                        });
                  //  return false;
            });
        });
    </script>
}

vidli_Full_App/Vidly/Views/Rentals/RentalForm.cshtml
@model Vidly.ViewModels.RentalFormViewModel

@{
    ViewBag.Title = "RentalForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RentalForm</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RentalFormViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedCustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => Model.SelectedCustomerID, Model.Customers, htmlAttributes: new { @class = "form-control" })
                @*@Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.SelectedCustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedMovieID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => Model.SelectedMovieID, Model.Movies, htmlAttributes: new { @class = "form-control" })
                @*@Html.EditorFor(model => model.MovieId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.SelectedMovieID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>